In [1]:
import pandas as pd
import numpy as np

In [2]:
diabetes_df=pd.read_csv('Dataset\\diabetes.csv')
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
diabetes_df.shape

(768, 9)

In [3]:
diabetes_df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
diabetes_df['Pregnancies'].value_counts()

1     135
0     111
2     103
3      75
4      68
5      57
6      50
7      45
8      38
9      28
10     24
11     11
13     10
12      9
14      2
15      1
17      1
Name: Pregnancies, dtype: int64

In [5]:
#finding the values with zero and replacing with NAN.

diabetes_data_copy=diabetes_df.copy(deep=True)
diabetes_data_copy[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']]=diabetes_data_copy[['Glucose','BloodPressure','SkinThickness','Insulin','BMI']].replace(0,np.NaN)
diabetes_data_copy.isnull().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [7]:
#mean -> Average value.
#meadian -> middle value.
#mode -> maximum value.

#filling the null values by mean and median

diabetes_data_copy['Glucose'].fillna(diabetes_data_copy['Glucose'].mean(),inplace=True)

diabetes_data_copy['BloodPressure'].fillna(diabetes_data_copy['BloodPressure'].mean(),inplace=True)

diabetes_data_copy['SkinThickness'].fillna(diabetes_data_copy['SkinThickness'].median(),inplace=True)

diabetes_data_copy['Insulin'].fillna(diabetes_data_copy['Insulin'].median(),inplace=True)

diabetes_data_copy['BMI'].fillna(diabetes_data_copy['BMI'].median(),inplace=True)

In [8]:
diabetes_data_copy.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
#Bucketting the pregenencies.
#changing the values greater than 3 to 4.

diabetes_data_copy[diabetes_data_copy.Pregnancies>3]=4

In [10]:
diabetes_data_copy['Pregnancies'].value_counts()

4    344
1    135
0    111
2    103
3     75
Name: Pregnancies, dtype: int64

In [11]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [12]:
x=diabetes_data_copy.drop(columns='Outcome') #x is independent variable (8 columns)

In [13]:
y=diabetes_data_copy['Outcome']  #y is dependent variable, we are going to perdict the outcome

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0,shuffle=True)

In [20]:
logistic_reg=LogisticRegression()
logistic_reg.fit(x_train,y_train)

F:\python\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
y_pred=logistic_reg.predict(x_test)

In [22]:
y_pred

array([1, 0, 4, 4, 0, 0, 4, 0, 0, 4, 0, 4, 4, 0, 4, 0, 4, 0, 4, 4, 4, 0,
       0, 0, 0, 1, 0, 4, 0, 4, 4, 0, 0, 1, 1, 4, 4, 0, 1, 1, 0, 0, 4, 1,
       1, 0, 0, 0, 4, 4, 4, 0, 4, 4, 0, 1, 0, 4, 0, 4, 4, 4, 0, 1, 1, 4,
       4, 0, 4, 4, 0, 4, 0, 4, 4, 4, 4, 4, 4, 0, 4, 0, 0, 0, 4, 4, 1, 1,
       4, 0, 0, 0, 0, 0, 1, 0, 4, 0, 4, 4, 0, 0, 4, 0, 0, 4, 0, 1, 0, 4,
       0, 4, 4, 0, 0, 4, 0, 1, 0, 4, 4, 4, 0, 4, 0, 0, 4, 4, 1, 0, 4, 4,
       0, 1, 4, 4, 1, 4, 0, 1, 0, 4, 0, 4, 4, 0, 4, 4, 0, 0, 4, 4, 0, 0,
       4, 4, 0, 0, 4, 4, 4, 4, 0, 0, 4, 0, 4, 0, 0, 0, 1, 4, 4, 0, 0, 4,
       4, 4, 4, 0, 4, 4, 0, 1, 4, 4, 0, 4, 1, 0, 0, 4, 4, 1, 0, 4, 4, 4,
       1, 4, 0, 1, 4, 4, 0, 0, 4, 0, 0, 1, 0, 0, 4, 1, 0, 4, 4, 1, 1, 0,
       4, 0, 0, 4, 0, 4, 4, 4, 0, 0, 4], dtype=int64)

In [23]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [24]:
print('Accuracy Score:',accuracy_score(y_test,y_pred))

Accuracy Score: 0.8441558441558441


In [25]:
results= confusion_matrix(y_test,y_pred)
print(results)

[[ 80  20   0]
 [ 16  10   0]
 [  0   0 105]]


In [26]:
#importing classifers models

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier

In [27]:
#defining many classifiers in a single dictonary

clfs={
    'LogisticRegression': LogisticRegression(),
    'RandomForest': RandomForestClassifier(),
    'SVM':SGDClassifier(),
    'KNN':KNeighborsClassifier()
}

In [28]:
#seperating the keys and values 

for clf,clf_name in zip(clfs.values(),clfs.keys()):
    clf.fit(x_train,y_train)
    y_pred=clf.predict(x_test)
    score=accuracy_score(y_test,y_pred)
    
    print(clf_name,"-->",score)

F:\python\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression --> 0.8441558441558441
RandomForest --> 0.9177489177489178
SVM --> 0.6883116883116883
KNN --> 0.8874458874458875


In [29]:
from sklearn.model_selection import cross_val_score

In [30]:
#cross validation.
accuracy_CR=cross_val_score(estimator=logistic_reg,X=x_test,y=y_test,cv=10)

F:\python\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
F:\python\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_L

In [31]:
accuracy_CR

array([0.875     , 0.82608696, 0.86956522, 1.        , 0.82608696,
       0.82608696, 0.86956522, 0.91304348, 0.91304348, 0.86956522])

In [32]:
#mean of accuracy score.
print(accuracy_CR.mean())

0.878804347826087


In [33]:
#standard deviation of the accuracy score.
print(accuracy_CR.std())

0.05063689357127077


In [41]:
#appending a value into the dataset and predicting the output 
input_var_pred=[[3,230,89,35,900,34,0.4,54]]

In [42]:
#predicting using logistic regression.
out_come=logistic_reg.predict(input_var_pred)

In [43]:
print(out_come)

[1]
